In [2]:
import pandas as pd 
import numpy as np 
from utils import preprocess
# path = r'D:\Practice\projects\WebScrapping\Glintsdata_221111_Vietnam.csv'
path = 'PATH_TO_DATAFILE'
df = pd.read_csv(path)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        1969 non-null   int64  
 1   job_title         1969 non-null   object 
 2   job_link          1969 non-null   object 
 3   company_name      1958 non-null   object 
 4   company_link      1951 non-null   object 
 5   salary            1208 non-null   object 
 6   currency          1213 non-null   object 
 7   category          1969 non-null   object 
 8   contract          1969 non-null   object 
 9   experience        1721 non-null   object 
 10  benefit           0 non-null      float64
 11  requirement       1956 non-null   object 
 12  industry          1433 non-null   object 
 13  company_size      1811 non-null   object 
 14  company_location  1417 non-null   object 
 15  job_location      1962 non-null   object 
 16  posted            1951 non-null   object 


In [5]:
for i in df.columns:
    print(i)
    display(df[i].unique())

Unnamed: 0


array([   0,    1,    2, ..., 1966, 1967, 1968], dtype=int64)

job_title


array(['[Glints 5 Ngày] Data Engineer', '[Glints 5 Ngày] Head Of Product',
       '[Glints 5 Ngày] Backend Developer', ..., 'Mobile Developer',
       'UI/UX Designer (Product Design)', 'Senior Pentester'],
      dtype=object)

job_link


array(['https://glints.com/vn/opportunities/jobs/glints-5-ngay-data-engineer/36ac33b0-e07e-4d6c-ad42-c25cded5722f',
       'https://glints.com/vn/opportunities/jobs/glints-5-ngay-head-of-product/b19f62fd-eeca-4a17-ad4d-5e734364b767',
       'https://glints.com/vn/opportunities/jobs/glints-5-ngay-backend-developer/d0ebdb90-b828-424d-ba97-d283c5fe371f',
       ...,
       'https://glints.com/vn/opportunities/jobs/mobile-developer/9ad147ec-6961-4215-a49d-6b44b53941e2',
       'https://glints.com/vn/opportunities/jobs/ui-ux-designer-product-design/36d42077-0c3f-4044-892f-424b1a36f3cf',
       'https://glints.com/vn/opportunities/jobs/senior-pentester/5d20c8dd-29b7-425f-bec8-7e82316faac3'],
      dtype=object)

company_name


array(['Bbv Vietnam Co., Ltd', 'Be Group', 'Poc Pharma', 'Elfie',
       'John Hu Migration Consulting Viet Nam', 'Cốc Cốc', 'Finan',
       'DRCOM', 'Công Ty CP Công Nghệ Sendo',
       ' CÔNG TY TÀI CHÍNH TRÁCH NHIỆM HỮU HẠN MB SHINSEI (MCREDIT)',
       'C2C TECH HUB', 'OKXE', 'Kiến Guru', 'Advesa Digital Solutions',
       'Kingfoodmart (A member of Seedcom group)',
       'Công ty cổ phần Giáo Dục và Công Nghệ Hùng Vương',
       'Schneider Electric Vietnam', 'Gene Solutions', 'One Mount',
       'Ghn Express', 'Viettel Big Data Analytics Center (DAC)',
       'Công ty Cổ Phần Markus Việt Nam ', 'GenKin', 'Gimasys',
       'Skylink Group', 'Prudential Vietnam Assurance Private Ltd',
       'Palazzo Club', 'Apollo Solutions', 'Công Ty Tnhh Puzzle Studio',
       'Công ty Cổ phần Công nghệ ISOFH', 'TK Media', 'Monkey Việt Nam',
       'Mcv Corporation', 'Công Ty Greenmazing', 'Vgames Studio',
       'Bss Group', 'MFast', 'Công ty Cổ Phần Galaxy Play',
       'Công Ty Toponseek', 'Cô

company_link


array(['https://glints.com/vn/companies/bbv-vietnam-co-ltd/404d66f8-15ed-4151-894e-0507abdddc14',
       'https://glints.com/vn/companies/be-group/6a190f56-1a16-4a44-84d7-f260eace4df1',
       'https://glints.com/vn/companies/poc-pharma/d544166b-1b55-400f-a344-30e9cbcf8c94',
       'https://glints.com/vn/companies/elfie/f3c32e5b-d039-49aa-8359-c4da1f55edd8',
       'https://glints.com/vn/companies/john-hu-migration-consulting-viet-nam/dc884e96-110b-482c-882b-40e7dc34a0a1',
       'https://glints.com/vn/companies/coc-coc/4089a7b2-c480-4aaa-aa13-bdc414cdf9f3',
       'https://glints.com/vn/companies/finan/7f174009-9dd1-491d-a556-65a83215698e',
       'https://glints.com/vn/companies/drcom/d90fac59-e8b3-43ea-b4e0-7181bcda088f',
       'https://glints.com/vn/companies/cong-ty-cp-cong-nghe-sendo/c2f4dc22-c6b9-452e-916f-a0d1cee3567b',
       'https://glints.com/vn/companies/cong-ty-tai-chinh-trach-nhiem-huu-han-mb-shinsei-mcredit/7d2df1bd-1a7f-4ed7-932b-a9add54305e9',
       'https://glints.

salary


array(['VND40.000.000/month', 'USD7.000 - 10.000/month',
       'USD1.000 - 4.000/month', 'USD3.500 - 5.500/month',
       'USD4.000/month', 'USD700 - 1.300/month',
       'VND15.000.000 - 25.000.000/month', nan, 'VND30.000.000/month',
       'VND38.000.000/month', 'VND25.000.000/month', 'IDR100 - 200/month',
       'USD1.300/month', 'VND16.000.000 - 20.000.000/month',
       'USD0 - 3.000/month', 'IDR7.000.000 - 9.000.000/month',
       'VND2.000.000 - 3.000.000/month', 'VND3.000.000/month',
       'VND11.999.900/month', 'VND10.000.000 - 20.000.000/month',
       'USD1.000 - 1.500/month', 'VND14.000.000/month',
       'VND8.000.000 - 15.000.000/month',
       'VND12.000.000 - 18.000.000/month',
       'VND8.000.000 - 16.000.000/month', 'USD2.000 - 2.500/month',
       'USD500 - 1.200/month', 'VND15.000.000/month',
       'USD500 - 1.400/month', 'USD500 - 800/month',
       'VND15.000.000 - 35.000.000/month',
       'VND10.000.000 - 25.000.000/month', 'USD1.500 - 2.000/month',
       '

currency


array(['VND', 'USD', nan, 'IDR', 'SGD', 'MYR', 'JPY'], dtype=object)

category


array(['Software Engineering', 'Product Management',
       'Business Development / Sales', 'Data Science', 'Engineering',
       'Marketing', 'Other', 'Finance', 'Administrative', 'Consulting',
       'Operations', 'Management', 'Language and Translation',
       'Human Resource', 'Media & Communications', 'Design', 'Education',
       'Legal', 'Healthcare', 'Hospitality and Travel'], dtype=object)

contract


array(['Việc làm fulltime', 'Thực Tập', 'Việc làm part time', 'Finance',
       'Việc làm freelance', 'Marketing', 'Operations',
       'Business Development / Sales', 'Administrative'], dtype=object)

experience


array(['3 - 5 năm kinh nghiệm', '5 - 10 năm kinh nghiệm',
       'Hơn 10 năm kinh nghiệm', '1 - 3 năm kinh nghiệm', nan,
       'Dưới một năm kinh nghiệm', 'Việc làm fulltime'], dtype=object)

benefit


array([nan])

requirement


array(['Interpersonal Skills,English,Analyzing skills,SQL,ETL Tools',
       'English,Strong Leadership Skills,Product Development',
       'Backend Developer,Data Structures,Critical Thinking,Algorithms,Problem-solving Skills',
       ..., 'JavaScript,React Native,Flutter,Typescript',
       'Ux Research,Design Thinking,UIUX Design',
       'Cybersecurity,OWASP,CEH,Network Security,IT Security,Networking,Python,Blue Team,CompTIA,Pentesting,Cyber-security,Cvss'],
      dtype=object)

industry


array([nan, 'Pharmaceuticals', 'Information Technology and Services',
       'Hospital & Health Care', 'Financial Services',
       'Consumer Services', 'Marketing and Advertising',
       'Primary/Secondary Education', 'Logistics and Supply Chain',
       'Computer Software', 'Media Production', 'Education Management',
       'Environmental Services', 'Market Research', 'Higher Education',
       'Cosmetics', 'Outsourcing/Offshoring', 'Plastics',
       'Consumer Electronics', 'Investment Banking', 'Food & Beverages',
       'Accounting', 'Online Media', 'Real Estate', 'Human Resources',
       'Investment Management', 'Leisure, Travel & Tourism', 'Internet',
       'Computer Games', 'Management Consulting', 'Apparel & Fashion',
       'Consumer Goods', 'Wholesale', 'Commercial Real Estate',
       'International Trade and Development', 'Wine and Spirits',
       'Health, Wellness and Fitness', 'Luxury Goods & Jewelry',
       'Telecommunications', 'Retail', 'Design', 'Entertainment',

company_size


array([nan, '201-500 nhân viên', '51-200 nhân viên', '11-50 nhân viên',
       '501 - 1000 nhân viên', '5001 - 10,000 nhân viên',
       '1001 - 5000 nhân viên', 'Tự kinh doanh', '1-10 nhân viên',
       '> 10,000 nhân viên'], dtype=object)

company_location


array([nan,
       'Địa chỉ văn phòngTầng 16, Tòa Nhà Sai Gon Tower, 29 Lê Duẩn, Phường Bến Nghé, Quận 1, Thành phố Hồ Chí Minh, Việt Nam.',
       'Địa chỉ văn phòng 50 Tôn Thất Đạm, Phường Nguyễn Thái Bình, Quận 1, Thành phố Hồ Chí Minh',
       'Địa chỉ văn phòngTầng 2, 124 Điện Biên Phủ, Phường Đa Kao, Quận 1, Thành phố Hồ Chí Minh, Việt Nam',
       'Địa chỉ văn phòng198/10E Điện Biên Phủ, Phường 15, Quận Bình Thạnh, TPHCM',
       'Địa chỉ văn phòng131 Xô Viết Nghệ Tĩnh, P17, Bình Thạnh, TPHCM',
       'Địa chỉ văn phòngĐường Số 8, Tân Thuận Đông, Quận 7, TPHCM',
       'Địa chỉ văn phòng2C12 Truong Sa Street, Ward 19, Binh Thanh Dist., HCM City',
       'Địa chỉ văn phòngTòa nhà Sao Mai - Tầng 11, số 19 Lê Văn Lương, P. Nhân Chính, Q. Thanh Xuân.',
       'Địa chỉ văn phòng351 / 58 Lê Văn Sỹ, Phường 13, Quận 3, Thành phố Hồ Chí Minh',
       'Địa chỉ văn phòngBế Văn Cấm, P. Tân Kiểng, Quận 7, Tp. Hồ Chí Minh',
       'Địa chỉ văn phòng Tòa Rivera Park, 69 Vũ Trọng Phụng, Thanh X

job_location


array(['Ho Chi Minh City', 'Hà Nội', 'Hà Nam', 'hủ Đức', 'Bình Dương',
       'Da Nang', 'Quận Bốn', 'Đồng Nai', 'Ái Tử', 'Quận Bình Thạnh',
       'Hải Phòng', 'Ðà Lạt', 'Cần Thơ', 'Buôn Ma Thuột', 'Nhơn Trạch',
       'Cầu Giấy', 'Biên Hòa', 'Phan Thiết', 'A Lưới', 'Kiên Giang', nan,
       'Đắk Lắk', 'An Nhơn', 'ân Phú', 'Nha Trang', 'Khánh Hòa',
       'Hai BàTrưng'], dtype=object)

posted


array(['7 ngày trước', '8 ngày trước', '11 ngày trước', '10 tháng trước',
       '3 ngày trước', '9 ngày trước', '14 ngày trước', '29 ngày trước',
       '2 tháng trước', '3 tháng trước', '7 tháng trước', '8 tháng trước',
       '4 tháng trước', '11 tháng trước', '2 ngày trước', 'hôm qua',
       '4 ngày trước', '31 ngày trước', '1 tháng trước', '5 tháng trước',
       '6 tháng trước', '30 ngày trước', '25 ngày trước', '12 ngày trước',
       '23 ngày trước', '28 ngày trước', '24 ngày trước', '22 ngày trước',
       '15 ngày trước', '16 ngày trước', '10 ngày trước', '1 năm trước',
       '18 ngày trước', nan, '17 ngày trước', '20 ngày trước',
       '5 ngày trước', '9 tháng trước', '26 ngày trước', '27 ngày trước',
       '6 ngày trước', '21 ngày trước', '13 ngày trước', '19 ngày trước'],
      dtype=object)

updated


array(['nhật 4 ngày trước', 'nhật 11 ngày trước', 'nhật 1 tháng trước',
       'nhật hôm qua', 'nhật 3 ngày trước', 'nhật 9 ngày trước',
       'nhật 1 giờ trước', 'nhật 14 ngày trước', 'nhật 29 ngày trước',
       'nhật 28 phút trước', 'nhật 2 giờ trước', 'nhật 19 ngày trước',
       'nhật 2 ngày trước', 'nhật 6 ngày trước', 'nhật 22 ngày trước',
       'nhật 5 ngày trước', 'nhật 2 tháng trước', 'nhật 3 phút trước',
       'nhật 16 ngày trước', 'nhật 7 ngày trước', 'nhật 30 ngày trước',
       'nhật 24 ngày trước', 'nhật 12 ngày trước', 'nhật 31 ngày trước',
       'nhật 8 phút trước', 'nhật 25 ngày trước', 'nhật 26 ngày trước',
       'nhật 17 ngày trước', 'nhật 15 ngày trước', 'nhật 13 ngày trước',
       'nhật 23 ngày trước', 'nhật 27 ngày trước', 'nhật 10 ngày trước',
       'nhật 3 tháng trước', 'nhật 8 ngày trước', 'nhật 12 giờ trước',
       'nhật 3 giờ trước', 'nhật 11 giờ trước', 'nhật 7 tháng trước',
       'nhật 9 giờ trước', 'nhật 4 tháng trước', 'nhật 1 năm trước',
      

scrapped_time


array(['2022-11-11 13:42:04', '2022-11-11 13:42:09',
       '2022-11-11 13:42:17', ..., '2022-11-11 16:48:11',
       '2022-11-11 16:48:28', '2022-11-11 16:48:37'], dtype=object)

payment_period


array(['month', nan, 'hour', 'year', 'project'], dtype=object)

lowerbound


array([4.00000e+07, 7.00000e+03, 1.00000e+03, 3.50000e+03, 4.00000e+03,
       7.00000e+02, 1.50000e+07,         nan, 3.00000e+07, 3.80000e+07,
       2.50000e+07, 1.00000e+02, 1.30000e+03, 1.60000e+07, 0.00000e+00,
       7.00000e+06, 2.00000e+06, 3.00000e+06, 1.19999e+07, 1.00000e+07,
       1.40000e+07, 8.00000e+06, 1.20000e+07, 2.00000e+03, 5.00000e+02,
       1.50000e+03, 1.20000e+03, 9.00000e+02, 6.00000e+02, 2.00000e+07,
       8.00000e+02, 1.80000e+07, 3.00000e+03, 1.50000e+01, 1.80000e+03,
       5.00000e+06, 3.70000e+07, 2.50000e+06, 4.00000e+06, 6.00000e+06,
       2.50000e+04, 1.00000e+04, 1.10000e+07, 1.00000e+06, 3.50000e+07,
       2.50000e+03, 3.00000e+02, 6.50000e+02, 4.50000e+02, 1.40000e+03,
       9.00000e+06, 5.00000e+07, 5.50000e+07, 2.30000e+07, 4.50000e+07,
       4.00000e+02, 2.40000e+03, 1.60000e+03, 2.00000e+02, 4.50000e+06,
       6.00000e+07, 5.10000e+07, 1.70000e+07, 2.30000e+03, 2.40000e+06,
       3.20000e+07, 5.99990e+06, 3.50000e+02, 6.50000e+07, 1.700

upperbound


array([4.000000e+07, 1.000000e+04, 4.000000e+03, 5.500000e+03,
       1.300000e+03, 2.500000e+07,          nan, 3.000000e+07,
       3.800000e+07, 2.000000e+02, 2.000000e+07, 3.000000e+03,
       9.000000e+06, 3.000000e+06, 1.199990e+07, 1.500000e+03,
       1.400000e+07, 1.500000e+07, 1.800000e+07, 1.600000e+07,
       2.500000e+03, 1.200000e+03, 1.400000e+03, 8.000000e+02,
       3.500000e+07, 2.000000e+03, 1.700000e+03, 1.000000e+03,
       2.000000e+01, 1.800000e+03, 1.000000e+07, 4.700000e+03,
       5.000000e+06, 3.700000e+07, 2.200000e+03, 1.300000e+07,
       8.000000e+06, 6.000000e+06, 2.500000e+04, 7.000000e+06,
       2.000000e+04, 2.001000e+03, 3.500000e+03, 1.700000e+07,
       1.000000e+06, 4.500000e+03, 4.000000e+02, 9.000000e+02,
       1.500010e+07, 3.300000e+03, 6.000000e+02, 1.000000e+02,
       5.000000e+07, 4.000000e+06, 1.900000e+07, 4.500000e+07,
       1.200000e+07, 2.000000e+06, 2.010000e+03, 6.500000e+07,
       2.600000e+07, 2.500000e+08, 9.500000e+02, 4.2000

average


array([4.000000e+07, 8.500000e+03, 2.500000e+03, 4.500000e+03,
       4.000000e+03, 1.000000e+03, 2.000000e+07,          nan,
       3.000000e+07, 3.800000e+07, 2.500000e+07, 1.500000e+02,
       1.300000e+03, 1.800000e+07, 1.500000e+03, 8.000000e+06,
       2.500000e+06, 3.000000e+06, 1.199990e+07, 1.500000e+07,
       1.250000e+03, 1.400000e+07, 1.150000e+07, 1.200000e+07,
       2.250000e+03, 8.500000e+02, 9.500000e+02, 6.500000e+02,
       1.750000e+07, 1.750000e+03, 1.450000e+03, 1.100000e+03,
       9.000000e+02, 2.250000e+07, 1.150000e+03, 7.500000e+02,
       3.000000e+03, 1.750000e+01, 1.800000e+03, 8.500000e+06,
       2.800000e+03, 2.400000e+03, 5.000000e+06, 3.700000e+07,
       1.050000e+03, 1.250000e+07, 1.600000e+03, 1.850000e+03,
       3.750000e+06, 7.500000e+06, 4.500000e+06, 6.000000e+06,
       2.500000e+04, 7.000000e+06, 1.000000e+07, 1.500000e+04,
       1.650000e+07, 1.050500e+03, 3.250000e+03, 2.000000e+03,
       2.100000e+07, 1.000000e+06, 3.650000e+07, 2.7500

In [ ]:

# Apply the function to the DataFrame
df[['salary_period', 'currency', 'lowerbound', 'upperbound', 'average']] = df['salary'].apply(preprocess.process_salary)

# Display the updated DataFrame
df

Unnamed: 0                                     job_title  \
0              0                 [Glints 5 Ngày] Data Engineer   
1              1               [Glints 5 Ngày] Head Of Product   
2              2             [Glints 5 Ngày] Backend Developer   
3              3  [Glints 5 Ngày] Senior/Lead Backend Engineer   
4              4                 [Glints 5 Ngày] Head of Sales   
...          ...                                           ...   
1964        1964                    Java developer (EDI tech)    
1965        1965                               Content Manager   
1966        1966                              Mobile Developer   
1967        1967               UI/UX Designer (Product Design)   
1968        1968                              Senior Pentester   

                                               job_link  \
0     https://glints.com/vn/opportunities/jobs/glint...   
1     https://glints.com/vn/opportunities/jobs/glint...   
2     https://glints.com/vn/opportunities/jobs/glint...   
3     https://glints.com/vn/opportunities/jobs/glint...   
4     https://glints.com/vn/opportunities/jobs/glint...   
...                                                 ...   
1964  https://glints.com/vn/opportunities/jobs/java-...   
1965  https://glints.com/vn/opportunities/jobs/conte...   
1966  https://glints.com/vn/opportunities/jobs/mobil...   
1967  https://glints.com/vn/opportunities/jobs/ui-ux...   
1968  https://glints.com/vn/opportunities/jobs/senio...   

                               company_name  \
0                      Bbv Vietnam Co., Ltd   
1                                  Be Group   
2                                Poc Pharma   
3                                     Elfie   
4     John Hu Migration Consulting Viet Nam   
...                                     ...   
1964                          Ekino Vietnam   
1965                          Anneco Agency   
1966                           Innomizetech   
1967               Advesa Digital Solutions   
1968       Bouygues Construction IT Vietnam   

                                           company_link  \
0     https://glints.com/vn/companies/bbv-vietnam-co...   
1     https://glints.com/vn/companies/be-group/6a190...   
2     https://glints.com/vn/companies/poc-pharma/d54...   
3     https://glints.com/vn/companies/elfie/f3c32e5b...   
4     https://glints.com/vn/companies/john-hu-migrat...   
...                                                 ...   
1964  https://glints.com/vn/companies/ekino-vietnam/...   
1965  https://glints.com/vn/companies/anneco-agency/...   
1966  https://glints.com/vn/companies/innomizetech/1...   
1967  https://glints.com/vn/companies/advesa-digital...   
1968  https://glints.com/vn/companies/bouygues-const...   

                                salary currency                      category  \
0                  VND40.000.000/month      VND          Software Engineering   
1              USD7.000 - 10.000/month      USD            Product Management   
2               USD1.000 - 4.000/month      USD          Software Engineering   
3               USD3.500 - 5.500/month      USD          Software Engineering   
4                       USD4.000/month      USD  Business Development / Sales   
...                                ...      ...                           ...   
1964                IDR100 - 200/month      IDR          Software Engineering   
1965                               NaN      NaN                         Other   
1966            USD1.000 - 2.500/month      USD          Software Engineering   
1967                    USD1.700/month      USD                        Design   
1968  VND30.000.000 - 50.000.000/month      VND          Software Engineering   

               contract              experience  ...       company_size  \
0     Việc làm fulltime   3 - 5 năm kinh nghiệm  ...                NaN   
1     Việc làm fulltime  5 - 10 năm kinh nghiệm  ...  201-500 nhân viên   
2     Việc làm fulltime   3 - 5 